spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/nettychat?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#    database: oracle
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.Oracle12cDialect
server:
  servlet:
    context-path: /susu
netty:
  port: 8090
  bossThread: 2
  workerThread: 2
  keepalive: true
  backlog: 100